superproject/blog/urls.py
from django.urls import path, include
from rest_framework import routers


from blog import views

app_name = "blog"

router = routers.DefaultRouter()
router.register("posts", views.PostViewSet)

urlpatterns = [
    path("", views.AllPostsView.as_view(), name = 'all'),
    path("<int:pk>/", views.SinglePostView.as_view(), name = 'single'),
    path("<int:pk>/delete/", views.DeletePostView.as_view(), name = 'delete'),
    path("new/", views.CreatePostView.as_view(), name = 'new'),
    path("<int:pk>/update/", views.UpdatePostView.as_view(), name = 'update'),
    path("api/", include(router.urls)),



]

superproject/project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from project.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task4/', include('task4.urls')),
    path('blog/', include('blog.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    ]

superproject/task4/urls.py
from django.urls import path, include

from task4.views import task
from task4.views import ShowNumbersView

urlpatterns = [
    path('', task),
    path('info/', ShowNumbersView.as_view())
]

superproject/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse_lazy


User = get_user_model()

class Post(models.Model):
    title = models.TextField()
    content = models.TextField(blank=True, null=True)
    hidden = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self) -> str:
        return reverse_lazy('blog:single', kwargs = {'pk': self.pk})

    def __str__(self):
        return self.title

superproject/task4/models.py
from django.db import models


class Numbers(models.Model):
    name = models.TextField(unique=True)
    n = models.BigIntegerField(default=0)

    def __repr__(self):
        return f'{self.__class__.__name__}()id={self.id}, name={self.name}, n={self.n}'

superproject/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from blog.models import Post
from rest_framework import serializers, viewsets


class BlogMixin:
    model = Post
    fields = ["title", "content", "hidden"]
    success_url = reverse_lazy('blog:all')


class OwnerMixin():
    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user)


class AllPostsView(BlogMixin, ListView):
    def get_queryset(self):
        return super().get_queryset().filter(hidden=False)


class SinglePostView(BlogMixin, DetailView):
    pass


class DeletePostView(LoginRequiredMixin, BlogMixin, OwnerMixin, DeleteView):
    pass


class CreatePostView(LoginRequiredMixin, BlogMixin, CreateView):
    model = Post
    fields = ["title", "content", "hidden"]

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return super().form_valid(form)


class UpdatePostView(LoginRequiredMixin, BlogMixin, OwnerMixin, UpdateView):
    pass


class PostSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Post
        depth = 1
        fields = ["id", "title", "content", "hidden", "author_id"]


class PostViewSet(viewsets.ModelViewSet):
    lookup_field = "id"
    queryset = Post.objects.all()
    serializer_class = PostSerializer

superproject/project/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import FormView


class SignUpView(FormView):
    extra_context = {"action": "Sign Up!"}
    form_class = UserCreationForm
    success_url = reverse_lazy("blog:all")
    template_name = "registration/login.html"

    def form_valid(self, form):
        form.save()
        user = authenticate(
            username=form.cleaned_data.get("username"),
            password=form.clean_password2(),
        )
        login(self.request, user)
        return super().form_valid(form)

superproject/task4/views.py
import json

from random import choice
from string import ascii_lowercase
from typing import Optional
from typing import Tuple
from typing import Union

from django.core.exceptions import PermissionDenied
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView

from task4.models import Numbers


def get_user_name(request: HttpRequest) -> Optional[str]:
    name = request.headers.get("x-user") or None
    return name


def set_user_name(response: HttpResponse, name: str) -> None:
    response.headers["x-user"] = name


def add_number(name: str, number: int):
    obj: Tuple[Numbers, bool] = Numbers.objects.get_or_create(name=name)
    rec, _created = obj
    rec.n += number
    rec.save()
    return rec.n


def validate_number(number: int) -> None:
    lower_bound, upper_bound = -100, 100
    if not (lower_bound <= number <= upper_bound):
        raise ValueError(
            f"number {number} is not in range {(lower_bound, upper_bound)}"
        )


def parse_payload(request: HttpRequest) -> Union[str, int, None]:
    if not request.body:
        raise ValueError("non-empty body is required")

    try:
        payload = json.loads(request.body)
    except json.JSONDecodeError as err:
        raise ValueError(f"malformed payload: {request.body!r} ({err})") from err

    if isinstance(payload, int):
        validate_number(payload)
    elif payload != "stop":
        raise ValueError(
            f"value {payload!r} is not acceptable: MUST be either int, or 'stop'"
        )

    return payload


class UnprocessableEntityResponse(JsonResponse):
    status_code = 422


@csrf_exempt
@require_http_methods(["POST"])
def task(request: HttpRequest) -> HttpResponse:
    name = get_user_name(request)
    if not name:
        raise PermissionDenied(json.dumps("header X-USER is not set"))

    try:
        payload = parse_payload(request)
    except ValueError as err:
        response = UnprocessableEntityResponse(str(err), safe=False)
    else:
        if isinstance(payload, int):
            current = add_number(name, payload)
        elif payload == "stop":
            current = add_number(name, 0)
        else:
            current = None

        response = JsonResponse(
            current,
            safe=False,
        )

    set_user_name(response, name)
    return response

class ShowNumbersView(ListView):
    template_name = 'task4/numbers.html'
    model = Numbers

superproject/blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if object.author == user %}
    <form method="POST">
        {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
    <p><a href="{% url 'blog:all' %}">(back to all posts)</a></p>
{% endif %}
</body>
</html>

superproject/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<article>
    <h1>{{ object.title }}</h1>
    <a href='{% url 'blog:all' %}'>(back to all posts)</a>
    {% if object.author == user %}
        <a href='{% url 'blog:update' object.pk %}'>(edit post)</a>
        <a href='{% url 'blog:delete' object.pk %}'>(delete post)</a>
    {% endif %}
    <hr>
    <p>{{ post.content|default:'(no content)'}}</p>
</article>
</body>
</html>

superproject/blog/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Confirm">
    </form>
{% endif %}
</body>
</html>

superproject/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Me: {{ user }}</p>
<div>
    <p>&#123; me: "{{ user }}" &#125;</p>
    <p><a href="{% url 'blog:post-list' %}">API</a></p>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">logOut()</a>
    {% else %}
     <a href="{% url 'login' %}">logIn()</a>
     <a href="{% url 'signup' %}">signUp()</a>
    {% endif %}
</div>
<article>
    <h1>All posts</h1>
    {% if not user.is_anonymous %}
        <a href="{% url 'blog:new' %}">New post</a>
    {% endif %}
    <hr>
    {% for post in object_list %}
        <section id="id_post_{{ post.pk }}">
            <a href="{{ post.get_absolute_url }}"><h2>{{ post.title }}</h2></a>
            <p>{{ post.content|default:"(no content)" }}</p>
            <p>Author: {{ post.author }}</p>
        </section>
    {% empty %}
        <p>(no posts)</p>
        {% if not user.is_anonymous %}
            <p><a href="{% url 'blog:new' %}">(create)</a></p>
        {% endif %}
    {% endfor %}
</article>
</body>
</html>

superproject/task4/templates/task4/numbers.html
<!DOCTYPE html>
<html lang="en">
<head>
<h1>
Мои логи!
</h1>
    <meta charset="UTF-8">
    <title>Сайт</title>
</head>
<body>
{{object_list}}
</body>
</html>